USE [master]
GO

/****** Object:  Database [accountingsoft]    Script Date: 18/05/2023 21:09:54 ******/
CREATE DATABASE [accountingsoft]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'accountingsoft', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\accountingsoft.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'accountingsoft_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\accountingsoft_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [accountingsoft].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [accountingsoft] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [accountingsoft] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [accountingsoft] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [accountingsoft] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [accountingsoft] SET ARITHABORT OFF 
GO

ALTER DATABASE [accountingsoft] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [accountingsoft] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [accountingsoft] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [accountingsoft] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [accountingsoft] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [accountingsoft] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [accountingsoft] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [accountingsoft] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [accountingsoft] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [accountingsoft] SET  ENABLE_BROKER 
GO

ALTER DATABASE [accountingsoft] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [accountingsoft] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [accountingsoft] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [accountingsoft] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [accountingsoft] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [accountingsoft] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [accountingsoft] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [accountingsoft] SET RECOVERY FULL 
GO

ALTER DATABASE [accountingsoft] SET  MULTI_USER 
GO

ALTER DATABASE [accountingsoft] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [accountingsoft] SET DB_CHAINING OFF 
GO

ALTER DATABASE [accountingsoft] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [accountingsoft] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [accountingsoft] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [accountingsoft] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [accountingsoft] SET QUERY_STORE = OFF
GO

ALTER DATABASE [accountingsoft] SET  READ_WRITE 
GO


